package tts

import (
	"strings"
	"testing"
)

func TestCredit(t *testing.T) {
	en, _ := VoiceFor("en", "female")
	es, _ := VoiceFor("es", "male")
	tests := []struct {
		name   string
		engine string
		voice  Voice
		by     string // generator; "" for the minimal sign-off
		host   string // bare domain; "" for the minimal sign-off
		want   string
	}{
		{"edge english", "edge-tts", en, "", "", "This episode was read by Sonia, from Microsoft Edge."},
		{"elevenlabs english", "elevenlabs", en, "", "", "This episode was read by Amelia, from Eleven Labs."},
		{"google english", "google-tts", en, "", "", "This episode was read by Neural Two A, from Google Cloud."},
		{"spanish is localized", "elevenlabs", es, "", "", "Este episodio fue narrado por Juan, de Eleven Labs."},
		{"spanish on edge", "edge-tts", es, "", "", "Este episodio fue narrado por Tomás, de Microsoft Edge."},
		// With a generator and host the credit names the source too.
		{"expanded english", "edge-tts", en, "nico", "radio.nicocesar.com",
			"Episode generated by nico on radio.nicocesar.com, voiced by Sonia, from Microsoft Edge."},
		{"expanded spanish", "elevenlabs", es, "nico", "radio.nicocesar.com",
			"Episodio generado por nico en radio.nicocesar.com, con la voz de Juan, de Eleven Labs."},
		// A half-known source (missing host or generator) stays minimal
		// rather than speaking "on ." or "by .".
		{"missing host falls back", "edge-tts", en, "nico", "",
			"This episode was read by Sonia, from Microsoft Edge."},
		{"missing generator falls back", "edge-tts", en, "", "radio.nicocesar.com",
			"This episode was read by Sonia, from Microsoft Edge."},
		// Rather than sign off with a slug the listener can't parse.
		{"unknown engine credits nothing", "festival", en, "nico", "radio.nicocesar.com", ""},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := Credit(tc.engine, tc.voice, tc.by, tc.host); got != tc.want {
				t.Errorf("Credit(%q) = %q, want %q", tc.engine, got, tc.want)
			}
		})
	}
}

// TestEveryVoiceCreditsOnEveryEngine is the real guard: a voice added to
// Voices without a spoken name for some engine would publish episodes
// that silently lose their sign-off, but only on the engine that happens
// to win the fallback chain that day.
func TestEveryVoiceCreditsOnEveryEngine(t *testing.T) {
	for _, v := range Voices {
		for engine := range providerNames {
			if Credit(engine, v, "nico", "radio.example.com") == "" {
				t.Errorf("no credit for %s/%s on %s", v.Language, v.Gender, engine)
			}
		}
	}
}

// TestCreditFormatPerLanguage catches a language added to Voices without
// a localized sign-off, which would otherwise ship a Spanish voice
// reading an English sentence.
func TestCreditFormatPerLanguage(t *testing.T) {
	for _, v := range Languages() {
		if _, ok := creditFormats[v.Language]; !ok {
			t.Errorf("language %q has no credit format", v.Language)
		}
		if _, ok := expandedCreditFormats[v.Language]; !ok {
			t.Errorf("language %q has no expanded credit format", v.Language)
		}
	}
}

// A sign-off is written by hand, in a language whoever added it may not
// read, and then spoken aloud. Sprintf does not fail on a format with the
// wrong number of verbs — it renders "%!s(MISSING)" straight into the
// audio — and every other credit test here only checks for a non-empty
// string, so this is the one that hears it.
func TestCreditRendersWithoutFormattingArtifacts(t *testing.T) {
	for _, v := range Languages() {
		for engine := range providerNames {
			for _, credit := range []string{
				Credit(engine, v, "", ""),
				Credit(engine, v, "nico", "radio.example.com"),
			} {
				if credit == "" {
					t.Errorf("no credit for %s on %s", v.Language, engine)
					continue
				}
				if strings.Contains(credit, "%!") || strings.Contains(credit, "%s") {
					t.Errorf("credit for %s on %s has a format error, and it is spoken out loud: %q",
						v.Language, engine, credit)
				}
			}
		}
	}
}

func TestByName(t *testing.T) {
	engines := []Engine{NewEdge()}
	if got := ByName(engines, "edge-tts"); got == nil {
		t.Error("ByName did not find edge-tts")
	}
	if got := ByName(engines, "elevenlabs"); got != nil {
		t.Errorf("ByName found %v for an absent engine", got)
	}
}
